version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/aws:2022.06
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to AWS S3 bucket
          command: |
            aws s3 sync build s3://www.greaper.net --delete --exact-timestamps
            aws cloudfront create-invalidation --distribution-id $GREAPER_WEBSITE_ID --paths '/*'

workflows:
  build-approve-deploy:
    jobs:
      - build:
          context: build-context
      - deploy:
          requires:
            - build
          context: build-context
          filters:
            branches:
              only:
                - master